server:
  port: 80

spring:
  application:
    name: cloud-order-org.spring.service
  cloud:
    consul:
      host: 10.10.10.2
      port: 8500
      discovery:
        service-name: ${spring.application.name}