server:
  port: 80

spring:
  application:
    name: cloud-order-org.spring.service

eureka:
  client:
    #true向Eureka server服务中心注册自己
    register-with-eureka: true
    #是否从Eureka server 抓起已有的注册信息,默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.org:7001/eureka,http://eureka7002.org:7002/eureka
  instance:
    instance-id: service80
    #访问路径可以显示IP地址
    prefer-ip-address: true