server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.10.10.2:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"