server:
  port: 9003

spring:
  application:
    name: nacos-alibaba-payment

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.10.10.2:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"