server:
  port: 3366


spring:
  application:
    name: cloud-config-client
  cloud:
    config:
      uri: http://localhost:3344
      label: master
      name: config
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.org:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"